apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mydeploy
  template:
    metadata:
      labels:
        name: mydeploy
    spec:
      containers:
      - name: mycontainer
        image: mubii2/ci-pipeline:latest   # replace with your Docker-image pushed on Dockerhub
        ports:
        - containerPort: 8080
