apiVersion: v1
kind: Service
metadata:
  name: myservice
  labels:
    app: mydeploy1
spec:
  type: NodePort
  selector:
    app: mydeploy1
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000  # Optional, Kubernetes will auto-assign if not specified
